# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "csv-mapper"
  s.version = "0.5.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Luke Pillow"]
  s.date = "2012-08-02"
  s.description = "CSV Mapper makes it easy to import data from CSV files directly to a collection of any type of Ruby object. The simplest way to create mappings is declare the names of the attributes in the order corresponding to the CSV file column order."
  s.email = "lpillow@gmail.com"
  s.extra_rdoc_files = [
    "History.txt",
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/csv-mapper.rb",
    "lib/csv-mapper/attribute_map.rb",
    "lib/csv-mapper/row_map.rb",
    "spec/csv-mapper/attribute_map_spec.rb",
    "spec/csv-mapper/row_map_spec.rb",
    "spec/csv-mapper_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/test.csv",
    "spec/test.tsv"
  ]
  s.homepage = "http://github.com/pillowfactory/csv-mapper"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "CsvMapper is a small library intended to simplify the common steps involved with importing CSV files to a usable form in Ruby."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec>, ["< 2.0.0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["< 2.0.0"])
      s.add_runtime_dependency(%q<fastercsv>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["< 2.0.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, ["< 2.0.0"])
      s.add_dependency(%q<fastercsv>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["< 2.0.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, ["< 2.0.0"])
    s.add_dependency(%q<fastercsv>, [">= 0"])
  end
end

